export const GENERAL_VALIDATION_RULES = {
  // Token
  TOKEN_MIN_LENGTH: 1,

  // Name
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 30,
  NAME_REGEX: /^[\p{L}\s]+$/u,

  // Password
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 30,
  PASSWORD_REGEX_LOWERCASE: '[a-z]+',
  PASSWORD_REGEX_UPPERCASE: '[A-Z]+',
  PASSWORD_REGEX_NUMBER: '[0-9]+',
  PASSWORD_REGEX_SPECIAL_CHARACTERS: '[@$!%*#?&]+',
}
