export const AlertCircle = () => <span>AlertCircle</span>
export const BarChart3 = () => <span>BarChart3</span>
export const CalendarIcon = () => <span>CalendarIcon</span>
export const ChevronDownIcon = () => <span>ChevronDownIcon</span>
export const ChevronLeft = () => <span>ChevronLeft</span>
export const ChevronRight = () => <span>ChevronRight</span>
export const ChevronsLeft = () => <span>ChevronsLeft</span>
export const ChevronsRight = () => <span>ChevronsRight</span>
export const ChevronUp = () => <span>ChevronUp</span>
export const LayoutDashboard = () => <span>LayoutDashboard</span>
export const LogOut = () => <span>LogOut</span>
export const Moon = () => <span>Moon</span>
export const MoonIcon = () => <span>MoonIcon</span>
export const PiggyBank = () => <span>PiggyBank</span>
export const Settings = () => <span>Settings</span>
export const Sun = () => <span>Sun</span>
export const SunIcon = () => <span>SunIcon</span>
export const Tag = () => <span>Tag</span>
export const Target = () => <span>Target</span>
export const User = () => <span>User</span>
export const Wallet = () => <span>Wallet</span>
export const X = () => <span>X</span>
